---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "invoice-backend-mock"
    integration: "invoice"
  name: "invoice-backend-mock-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "invoice-backend-mock"
        integration: "invoice"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env:
          - name: ecomm_backend_invoice_sftp_host
            value: "refund-sftp-headless-service.default.svc.cluster.local"
          - name: ecomm_backend_invoice_sftp_port
            value: "22"    
          - name: ecomm_backend_invoice_sftp_username
            valueFrom:
              secretKeyRef:
                name: ecomm-back-end-sftp-secret
                key: username 
          - name: ecomm_backend_invoice_sftp_password
            valueFrom:
                secretKeyRef:
                  name: ecomm-back-end-sftp-secret
                  key: password 
          - name: ecomm_backend_invoice_sftp_path
            value: "/var/sftp/invoice"   
          - name: ecomm_backend_invoice_etl_interval
            value: "10000" 
          - name: ecomm_backend_invoice_etl_initialDelay
            value: "500"                  
        envFrom: []
        image: "rajkumar/invoice-backend-mock:0.1.0"
        imagePullPolicy: "Always"
        name: "invoice-backend-mock-deployment"
        ports:             
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
