---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "order-signal-backend-mock"
  name: "order-signal-backend-mock-service"
  namespace: "default"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 8280
    name: http               
  selector:
    app: "order-signal-backend-mock"
