---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "refund-backend-mock"
  name: "refund-backend-mock-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "refund-backend-mock"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env:
          - name: ecomm_backend_refund_sftp_host
            value: "refund-sftp-headless-service.default.svc.cluster.local"
          - name: ecomm_backend_refund_sftp_port
            value: "22"    
          - name: ecomm_backend_refund_sftp_username
            value: "ecomm0xxx" 
          - name: ecomm_backend_refund_sftp_password
            value: "ec0mmoxxx" 
          - name: ecomm_backend_refund_sftp_path
            value: "/Users/ecomm0xxx/projects/ecomm/sftp/refund"     
          - name: ecomm_backend_refund_etl_interval
            value: "10000" 
          - name: ecomm_backend_refund_etl_initialDelay
            value: "500"                  
        envFrom: []
        image: "rajkumar/refund-backend-mock:0.6.0"
        imagePullPolicy: "IfNotPresent"
        name: "refund-backend-mock-deployment"
        ports:             
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
